language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: Uk1HihqhViwAdABAqXUzesDWyfgZNZ+OWtyP6jnh5x17EyPvXkjC8GXQVatrxsuvsmE8GJqpIbS0GLxqB2I1gVnSRWj773yJakYZCr/A230wNEjpZqsWvIOQ9DZa4IXNuzBa9tpElq+YvmmaQ++CJtJfEzM1imMR6bsGqtkj1mc=
  - secure: WD9gDRcv/olMIced4rzn2lvpYiRvIOfOSmmKB90tpCXesGo6rk9SVqeRqs+CR7DqONx0oSP0ozEQnxjj26SqELVTgHAEKjR8IC5rqjFAY4LELlMSQo5EhCIaSpwQBA78ehCeZyL1Xmzz0KR+FrXTBFAGAyuCh7Yim92/nmaKtEU=
